// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1649857328);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1649857088);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1649857208);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 419840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "EG");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1649857329);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"086ca1be-9bde-4106-8563-3dd10b8adefc\",\"default-theme@mozilla.org\":\"0c1eb217-e245-414d-a291-7db469d6716c\",\"google@search.mozilla.org\":\"9d9e295c-ebcd-4655-a90d-01d11e5a82bd\",\"amazondotcom@search.mozilla.org\":\"4f75fef0-3c7c-492c-9497-82b7e5affad5\",\"bing@search.mozilla.org\":\"60cc5c7b-8b4a-422b-8de4-e6781fb7857e\",\"ddg@search.mozilla.org\":\"c6beb19c-561f-4166-98c8-6a535da20d4b\",\"twitter@search.mozilla.org\":\"e148cc9f-6612-4f16-a90c-9b4670f2f903\",\"wikipedia@search.mozilla.org\":\"6e70d23c-2ea2-497d-8393-d7514c6b6354\"}");
user_pref("idle.lastDailyNotification", 1649857343);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "42a1ee2b-e808-453c-92ca-e32842b725d");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1649857343);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "2ff3908c-3fd1-4bad-a4c2-06488b25b91e");
user_pref("services.settings.clock_skew_seconds", -3);
user_pref("services.settings.last_etag", "\"1649856518949\"");
user_pref("services.settings.last_update_seconds", 1649857211);
user_pref("services.settings.main.hijack-blocklists.last_check", 1649857211);
user_pref("services.settings.main.language-dictionaries.last_check", 1649857211);
user_pref("services.settings.main.sites-classification.last_check", 1649857211);
user_pref("services.settings.security.onecrl.checked", 1649857211);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1649857343);
user_pref("toolkit.telemetry.cachedClientID", "4e1aaf5d-fcc1-4d34-8cea-19075e97a3a5");
user_pref("toolkit.telemetry.prompted", 2);
